replicaCount: 1

image:
  repository: ghcr.io/awzmb/devbox
  tag: "main"
  pullPolicy: Always

imagePullSecrets: []

serviceAccount:
  create: true

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add: ["NET_ADMIN"]

persistentVolumeClaim:
  storageClass: longhorn
  storageSizeHome: 2Gi
  storageSizeConfig: 10Gi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
     cert-manager.io/cluster-issuer: letsencrypt-prod
     nginx.ingress.kubernetes.io/ssl-redirect: "true"
     nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
     nginx.ingress.kubernetes.io/limit-rps: "60"
  hosts:
    - host: codebox.awzm.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: letsencrypt-codebox
      hosts:
        - codebox.awzm.sh

autoscaling:
  enabled: false
