kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "codebox.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSizeConfig | quote }}
  storageClassName: "{{ .Values.persistentVolumeClaim.storageClass }}"
